# OOP

instance & attribute --> örnek ve özellik


In [12]:
class SuperKahraman():
    def __init__(self): #initilazier, başlatma fonksiyonu, yapıcı fonksiyon
        print("init çağırıldı")

shift + enter hücreyi kapatır ve çalıştırır

In [ ]:
superman = SuperKahraman()

init çağırıldı


In [17]:
class SuperKahraman():
    def __init__(self, isim, yas, meslek): #initilazier, başlatma fonksiyonu, yapıcı fonksiyon
        print("init çağırıldı")
        self.isim = isim
        self.yas = yas
        self.meslek = meslek

In [27]:
superman = SuperKahraman("superman", 30, "gazeteci")

init çağırıldı


In [16]:
superman.yas

30

In [30]:
class SuperKahraman():
    ozelGuc = "" #zorunlu bir özellik olmadığında bu şekilde eklenebilir
    def __init__(self, isim, yas, meslek): #initilazier, başlatma fonksiyonu, yapıcı fonksiyon
        print("init çağırıldı")
        self.isim = isim
        self.yas = yas
        self.meslek = meslek

    def ornekMethod(self):
        print("ornek method")

    def ornekMethod2(self):
        #print(f"ben süperkahramanım ve mesleğim: {meslek}" ) bu çalışmaz, hangi meslek olduğunu bilemez
        print(f"ben süperkahramanım ve mesleğim: {self.meslek}" )


superman = SuperKahraman("superman", 30, "gazeteci")

init çağırıldı


In [31]:
superman.ornekMethod

<bound method SuperKahraman.ornekMethod of <__main__.SuperKahraman object at 0x74605a5ad840>>

In [32]:
superman.ornekMethod2()

ben süperkahramanım ve mesleğim: gazeteci


In [38]:
class Kopek():

    def __init__(self, yas = 1): #default değere sahip init
        self.yas = yas
    
    def kopekInsanYasi(self):
        self.insanYasi = self.yas*7
        print(f"köpeğin insan yaşı {self.insanYasi}")

    def kopekInsanYasi2(self):
        return self.yas*7
        


In [ ]:
class Kopek():

    yilCarpani = 7 #tek tek yıl çarpanını aramamak için attribute olarak ekledik

    def __init__(self, yas = 1): #default değere sahip init
        self.yas = yas
        #self.insanYasi = yas * 7
    
    def kopekInsanYasi(self):
        return self.yas * Kopek.yilCarpani
        #return self.yas * self.yilCarpani

In [37]:
ares = Kopek(3)
ares.kopekInsanYasi()

köpeğin insan yaşı 21


### inheritance

In [39]:
class Hayvan():
    def __init__(self):
        print("hayvan sınıfı, init")

    def method1(self):
        print("hayvan sınıfı, method1")
    
    def method2(self):
        print("hayvan sınıfı, method2")

In [53]:
class Kedi(Hayvan):
    def __init__(self):
        print("Kedi sınıfı, init")
        Hayvan.__init__(self)  

    def miyavla(self):
        print("miyyav")

    #override
    def method1(self):
        #return super().method1() --> üst sınıfın method1'i çağırılıyor
        print("kedi sınıfının method1'i")

In [54]:
kedi = Kedi()

Kedi sınıfı, init
hayvan sınıfı, init


In [55]:
kedi.method1() #kedi sınıfında methodlar olmadığı halde erişebiliyoruz

kedi sınıfının method1'i


In [49]:
kedi.miyavla()

miyyav


### polymorphism

aynı isimli fonksiyonların farklı amaçlara hizmet etmesi

In [57]:
class Elma():
    def __init__(self, isim):
        self.isim = isim

    def bilgiVer(self):
        return self.isim + " 100 kaloridir"

In [56]:
class Muz():
    def __init__(self, isim):
        self.isim = isim

    def bilgiVer(self):
        return self.isim + " 150 kaloridir"

In [58]:
elma = Elma("elma")
elma.bilgiVer()

'elma 100 kaloridir'

In [59]:
muz = Muz("muz")
muz.bilgiVer()

'muz 150 kaloridir'

In [60]:
meyveListesi = [elma, muz]

In [61]:
for meyve in meyveListesi:
    print(meyve.bilgiVer())

elma 100 kaloridir
muz 150 kaloridir


In [62]:
def bilgiAl(meyve):
    print(meyve.bilgiVer())

In [63]:
bilgiAl(muz)

muz 150 kaloridir


In [64]:
bilgiAl(elma)

elma 100 kaloridir


### özel methodlar

special methods (magic methods) in python


In [65]:
class Meyve():
    def __init__(self, isim, kalori):
        self.kalori = kalori
        self.isim = isim

In [66]:
muz = Meyve("muz", 200)

In [67]:
print(muz)

In [68]:
liste = [1,2,3,4.5, "a"]
print(liste)

[1, 2, 3, 4.5, 'a']


In [69]:
len(liste)

5

In [70]:
len(muz)

TypeError: object of type 'Meyve' has no len()

In [74]:
class Meyve():
    def __init__(self, isim, kalori):
        self.kalori = kalori
        self.isim = isim

    #print
    def __str__(self):
        return f"{self.isim}"
    
    def __len__(self):
        return self.kalori


muz = Meyve("muz", 200)

In [75]:
print(muz)

muz


In [76]:
len(muz)

200

In [77]:
elma = Meyve("elma", 150)

In [78]:
len(elma)

150

### hataları ele almak

try & except & else & finally

In [79]:
while True:
    try:
        benimInt = int(input("numara giriniz: "))
    except:
        print("sayılarla numara giriniz")
        continue
    else: #try bloğunda istenen olunca çağırılıyor
        print("teşekkürler")
        break
    finally:
        print("finally çağırıldı")

sayılarla numara giriniz
finally çağırıldı


# NUMPY

lineer cebir kütüphanesi

diğer kütüphanelere göre hızlı işlem yapıyor o yüzden diğer kütüphaneler numpy kullanır

In [1]:
import numpy as np

In [2]:
liste = [20,30,40]

In [3]:
type(liste)

list

In [4]:
#listeden numpy dizisine geçiş
np.array(liste)

array([20, 30, 40])

In [5]:
matrix = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
type(matrix)

list

In [7]:
np.array(matrix)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [8]:
# a-range
list(range(0,10))
np.arange(0,10) #10 dahil değil


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2) #10 dahil değil

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#linspace
#belirtilen numaralar arasında eşit aralık olacak şekilde dizi oluşturuyor

np.linspace(0,20,7) #0 ile 20 arasında eşit aralıklı 7 sayı oluştur

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [17]:
np.eye(3) #lineer cebirde bunu kullanıyorduk ama adını hatırlamıyorum

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.randn(5)  #normal dağılıma uygun veriler çıkartmaya çalışıyor

array([-1.37802678, -0.94046099, -0.10223295, -0.05824297,  1.21342897])

In [20]:
np.random.randn(4,4) 

array([[ 2.40866136, -0.31344943,  0.35180457, -0.61901733],
       [-0.44695363, -1.63118156, -1.02201691,  0.15124002],
       [-0.6624816 ,  0.77116451,  2.14487166, -0.23232819],
       [-0.55952317, -0.75043453, -2.1590875 ,  1.81662928]])

In [22]:
np.random.randint(5,50) #tek değer döndürüyor, son sayı dahil değil

37

In [23]:
np.random.randint(5,50,10)

array([39, 38, 49, 48, 16, 10, 38, 37, 16, 34])

In [31]:
atama = np.random.randint(5,50,10)

In [35]:
atama

array([30, 43, 38, 24, 17, 43,  5, 10,  6,  6])

In [28]:
atama.ndim

1

In [29]:
atama2 = atama.reshape(2,5)

In [30]:
atama2.ndim

2

In [36]:
atama.max()

43

In [33]:
atama.min()

5

In [38]:
atama.argmax() #max değerin hangi indexte olduğunu döndürür

1

In [40]:
atama.shape #parantez yok çünkü ATTRIBUTE

(10,)

In [41]:
array = np.arange(0,10)

In [42]:
array[5]

5

In [43]:
array[3:5]

array([3, 4])

In [44]:
array[3:8] = -5

In [45]:
array

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9])

In [46]:
array2 = np.arange(0,24)

In [47]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
scliced = array2[4:9] #bu atamada aynı bellek adresi işaret edilir, copy() kullanılmalı

In [49]:
scliced

array([4, 5, 6, 7, 8])

In [50]:
#scliced[0:] = 700
scliced[:] = 700

In [51]:
scliced

array([700, 700, 700, 700, 700])

In [66]:
#matrix
liste = [[10,20,30],[40,50,60],[70,80,90]]
matrisDizisi = np.array(liste)

In [61]:
matrisDizisi

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [62]:
matrisDizisi[0]

array([10, 20, 30])

In [63]:
matrisDizisi[1][2]
matrisDizisi[1,2] #ikisi aynı 

40

In [67]:
matrisDizisi[1:,2]

array([60, 90])

In [68]:
matrisDizisi[2:,2:]

array([[90]])

In [69]:
yeniListe = [[1,2,3,4,5],[6,7,8,9,13],[10,11,12,14,15],[16,17,18,19,20]]

In [70]:
yenimatris = np.array(yeniListe)

In [72]:
yenimatris[[2,2,0]] #fancy index, index yerine liste veriyoruz, o indekslere göre dizi oluşturuyor

array([[10, 11, 12, 14, 15],
       [10, 11, 12, 14, 15],
       [ 1,  2,  3,  4,  5]])

In [74]:
yeniDizi =np.random.randint(1,100,20)

In [75]:
yeniDizi

array([92, 42, 61, 31, 83, 23,  4, 67, 67, 55, 81,  3, 33, 55, 58, 57,  1,
       79, 31,  8])

In [76]:
yeniDizi > 24

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False])

In [77]:
sonucDizisi = yeniDizi > 24

In [78]:
sonucDizisi

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False])

In [79]:
yeniDizi[sonucDizisi]
yeniDizi[yeniDizi > 24]

#ikisi aynı, filtreleme sağlıyor

array([92, 42, 61, 31, 83, 67, 67, 55, 81, 33, 55, 58, 57, 79, 31])

In [80]:
sonDizi = np.arange(0,24)

In [81]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [83]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [85]:
sonDizi / sonDizi
#0 bölmede sistemi çökertmek yerine böyle bir şey yok deyip nan kullanıyor

/tmp/ipykernel_55695/2918049620.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [87]:
np.max(sonDizi)

23

In [88]:
np.min(sonDizi)

0