# OOP

instance & attribute --> örnek ve özellik


In [12]:
class SuperKahraman():
    def __init__(self): #initilazier, başlatma fonksiyonu, yapıcı fonksiyon
        print("init çağırıldı")

shift + enter hücreyi kapatır ve çalıştırır

In [ ]:
superman = SuperKahraman()

init çağırıldı


In [17]:
class SuperKahraman():
    def __init__(self, isim, yas, meslek): #initilazier, başlatma fonksiyonu, yapıcı fonksiyon
        print("init çağırıldı")
        self.isim = isim
        self.yas = yas
        self.meslek = meslek

In [27]:
superman = SuperKahraman("superman", 30, "gazeteci")

init çağırıldı


In [16]:
superman.yas

30

In [30]:
class SuperKahraman():
    ozelGuc = "" #zorunlu bir özellik olmadığında bu şekilde eklenebilir
    def __init__(self, isim, yas, meslek): #initilazier, başlatma fonksiyonu, yapıcı fonksiyon
        print("init çağırıldı")
        self.isim = isim
        self.yas = yas
        self.meslek = meslek

    def ornekMethod(self):
        print("ornek method")

    def ornekMethod2(self):
        #print(f"ben süperkahramanım ve mesleğim: {meslek}" ) bu çalışmaz, hangi meslek olduğunu bilemez
        print(f"ben süperkahramanım ve mesleğim: {self.meslek}" )


superman = SuperKahraman("superman", 30, "gazeteci")

init çağırıldı


In [31]:
superman.ornekMethod

<bound method SuperKahraman.ornekMethod of <__main__.SuperKahraman object at 0x74605a5ad840>>

In [32]:
superman.ornekMethod2()

ben süperkahramanım ve mesleğim: gazeteci


In [38]:
class Kopek():

    def __init__(self, yas = 1): #default değere sahip init
        self.yas = yas
    
    def kopekInsanYasi(self):
        self.insanYasi = self.yas*7
        print(f"köpeğin insan yaşı {self.insanYasi}")

    def kopekInsanYasi2(self):
        return self.yas*7
        


In [ ]:
class Kopek():

    yilCarpani = 7 #tek tek yıl çarpanını aramamak için attribute olarak ekledik

    def __init__(self, yas = 1): #default değere sahip init
        self.yas = yas
        #self.insanYasi = yas * 7
    
    def kopekInsanYasi(self):
        return self.yas * Kopek.yilCarpani
        #return self.yas * self.yilCarpani

In [37]:
ares = Kopek(3)
ares.kopekInsanYasi()

köpeğin insan yaşı 21


::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.

### inheritance

In [39]:
class Hayvan():
    def __init__(self):
        print("hayvan sınıfı, init")

    def method1(self):
        print("hayvan sınıfı, method1")
    
    def method2(self):
        print("hayvan sınıfı, method2")

In [53]:
class Kedi(Hayvan):
    def __init__(self):
        print("Kedi sınıfı, init")
        Hayvan.__init__(self)  

    def miyavla(self):
        print("miyyav")

    #override
    def method1(self):
        #return super().method1() --> üst sınıfın method1'i çağırılıyor
        print("kedi sınıfının method1'i")

In [54]:
kedi = Kedi()

Kedi sınıfı, init
hayvan sınıfı, init


In [55]:
kedi.method1() #kedi sınıfında methodlar olmadığı halde erişebiliyoruz

kedi sınıfının method1'i


In [49]:
kedi.miyavla()

miyyav


::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.

### polymorphism

aynı isimli fonksiyonların farklı amaçlara hizmet etmesi

In [57]:
class Elma():
    def __init__(self, isim):
        self.isim = isim

    def bilgiVer(self):
        return self.isim + " 100 kaloridir"

In [56]:
class Muz():
    def __init__(self, isim):
        self.isim = isim

    def bilgiVer(self):
        return self.isim + " 150 kaloridir"

In [58]:
elma = Elma("elma")
elma.bilgiVer()

'elma 100 kaloridir'

In [59]:
muz = Muz("muz")
muz.bilgiVer()

'muz 150 kaloridir'

In [60]:
meyveListesi = [elma, muz]

In [61]:
for meyve in meyveListesi:
    print(meyve.bilgiVer())

elma 100 kaloridir
muz 150 kaloridir


In [62]:
def bilgiAl(meyve):
    print(meyve.bilgiVer())

In [63]:
bilgiAl(muz)

muz 150 kaloridir


In [64]:
bilgiAl(elma)

elma 100 kaloridir


::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.

### özel methodlar

special methods (magic methods) in python


In [65]:
class Meyve():
    def __init__(self, isim, kalori):
        self.kalori = kalori
        self.isim = isim

In [66]:
muz = Meyve("muz", 200)

In [67]:
print(muz)

In [68]:
liste = [1,2,3,4.5, "a"]
print(liste)

[1, 2, 3, 4.5, 'a']


In [69]:
len(liste)

5

In [70]:
len(muz)

TypeError: object of type 'Meyve' has no len()

In [74]:
class Meyve():
    def __init__(self, isim, kalori):
        self.kalori = kalori
        self.isim = isim

    #print
    def __str__(self):
        return f"{self.isim}"
    
    def __len__(self):
        return self.kalori


muz = Meyve("muz", 200)

In [75]:
print(muz)

muz


In [76]:
len(muz)

200

In [77]:
elma = Meyve("elma", 150)

In [78]:
len(elma)

150

::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.

### hataları ele almak

try & except & else & finally

In [79]:
while True:
    try:
        benimInt = int(input("numara giriniz: "))
    except:
        print("sayılarla numara giriniz")
        continue
    else: #try bloğunda istenen olunca çağırılıyor
        print("teşekkürler")
        break
    finally:
        print("finally çağırıldı")

sayılarla numara giriniz
finally çağırıldı


--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;

# NUMPY

lineer cebir kütüphanesi

diğer kütüphanelere göre hızlı işlem yapıyor o yüzden diğer kütüphaneler numpy kullanır

In [1]:
import numpy as np

In [2]:
liste = [20,30,40]

In [3]:
type(liste)

list

In [4]:
#listeden numpy dizisine geçiş
np.array(liste)

array([20, 30, 40])

In [5]:
matrix = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
type(matrix)

list

In [7]:
np.array(matrix)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [8]:
# a-range
list(range(0,10))
np.arange(0,10) #10 dahil değil


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2) #10 dahil değil

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#linspace
#belirtilen numaralar arasında eşit aralık olacak şekilde dizi oluşturuyor

np.linspace(0,20,7) #0 ile 20 arasında eşit aralıklı 7 sayı oluştur

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [17]:
np.eye(3) #lineer cebirde bunu kullanıyorduk ama adını hatırlamıyorum

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.randn(5)  #normal dağılıma uygun veriler çıkartmaya çalışıyor

array([-1.37802678, -0.94046099, -0.10223295, -0.05824297,  1.21342897])

In [20]:
np.random.randn(4,4) 

array([[ 2.40866136, -0.31344943,  0.35180457, -0.61901733],
       [-0.44695363, -1.63118156, -1.02201691,  0.15124002],
       [-0.6624816 ,  0.77116451,  2.14487166, -0.23232819],
       [-0.55952317, -0.75043453, -2.1590875 ,  1.81662928]])

In [22]:
np.random.randint(5,50) #tek değer döndürüyor, son sayı dahil değil

37

In [23]:
np.random.randint(5,50,10)

array([39, 38, 49, 48, 16, 10, 38, 37, 16, 34])

In [31]:
atama = np.random.randint(5,50,10)

In [35]:
atama

array([30, 43, 38, 24, 17, 43,  5, 10,  6,  6])

In [28]:
atama.ndim

1

In [29]:
atama2 = atama.reshape(2,5)

In [30]:
atama2.ndim

2

In [36]:
atama.max()

43

In [33]:
atama.min()

5

In [38]:
atama.argmax() #max değerin hangi indexte olduğunu döndürür

1

In [40]:
atama.shape #parantez yok çünkü ATTRIBUTE

(10,)

In [41]:
array = np.arange(0,10)

In [42]:
array[5]

5

In [43]:
array[3:5]

array([3, 4])

In [44]:
array[3:8] = -5

In [45]:
array

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9])

In [46]:
array2 = np.arange(0,24)

In [47]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
scliced = array2[4:9] #bu atamada aynı bellek adresi işaret edilir, copy() kullanılmalı

In [49]:
scliced

array([4, 5, 6, 7, 8])

In [50]:
#scliced[0:] = 700
scliced[:] = 700

In [51]:
scliced

array([700, 700, 700, 700, 700])

In [66]:
#matrix
liste = [[10,20,30],[40,50,60],[70,80,90]]
matrisDizisi = np.array(liste)

In [61]:
matrisDizisi

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [62]:
matrisDizisi[0]

array([10, 20, 30])

In [63]:
matrisDizisi[1][2]
matrisDizisi[1,2] #ikisi aynı 

40

In [67]:
matrisDizisi[1:,2]

array([60, 90])

In [68]:
matrisDizisi[2:,2:]

array([[90]])

In [69]:
yeniListe = [[1,2,3,4,5],[6,7,8,9,13],[10,11,12,14,15],[16,17,18,19,20]]

In [70]:
yenimatris = np.array(yeniListe)

In [72]:
yenimatris[[2,2,0]] #fancy index, index yerine liste veriyoruz, o indekslere göre dizi oluşturuyor

array([[10, 11, 12, 14, 15],
       [10, 11, 12, 14, 15],
       [ 1,  2,  3,  4,  5]])

In [74]:
yeniDizi =np.random.randint(1,100,20)

In [75]:
yeniDizi

array([92, 42, 61, 31, 83, 23,  4, 67, 67, 55, 81,  3, 33, 55, 58, 57,  1,
       79, 31,  8])

In [76]:
yeniDizi > 24

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False])

In [77]:
sonucDizisi = yeniDizi > 24

In [78]:
sonucDizisi

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False])

In [79]:
yeniDizi[sonucDizisi]
yeniDizi[yeniDizi > 24]

#ikisi aynı, filtreleme sağlıyor

array([92, 42, 61, 31, 83, 67, 67, 55, 81, 33, 55, 58, 57, 79, 31])

In [80]:
sonDizi = np.arange(0,24)

In [81]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [83]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [85]:
sonDizi / sonDizi
#0 bölmede sistemi çökertmek yerine böyle bir şey yok deyip nan kullanıyor

/tmp/ipykernel_55695/2918049620.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [87]:
np.max(sonDizi)

23

In [88]:
np.min(sonDizi)

0

--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;--;

# PANDAS

### series

In [90]:
import numpy as np
import pandas as pd

In [91]:
sozluk = {"atil":50, "zeynep":40, "mehmet":30} 

In [92]:
pd.Series(sozluk)

atil      50
zeynep    40
mehmet    30
dtype: int64

In [93]:
yaslar = [50,40,30]
isimler = ["atil","zeynep","mehmet"]

pd.Series(yaslar, isimler)
pd.Series(data = yaslar, index = isimler)

atil      50
zeynep    40
mehmet    30
dtype: int64

In [94]:
numpyDizisi = np.array([50,40,30])
pd.Series(numpyDizisi)

pd.Series(numpyDizisi, isimler)

atil      50
zeynep    40
mehmet    30
dtype: int64

In [96]:
pd.Series(["atil","atlas","osman"],["bir","iki","uc"])

bir     atil
iki    atlas
uc     osman
dtype: object

In [97]:
yarismaSonucu1 = pd.Series([10,5,11],["atil","atlas","osman"]) #burdaki isimler index

In [98]:
yarismaSonucu2 = pd.Series([20,10,8],["atil","atlas","osman"])

In [99]:
yarismaSonucu2["atlas"]

10

In [100]:
sonSonuc = yarismaSonucu1 + yarismaSonucu2

In [101]:
sonSonuc

atil     30
atlas    15
osman    19
dtype: int64

In [102]:
farkliSeri1 = pd.Series([20,30,40,50],["a","b","c","d"])
farkliSeri2 = pd.Series([2,3,4,5],["e","f","g","d"])

In [103]:
farkliSeri1 + farkliSeri2

a     NaN
b     NaN
c     NaN
d    55.0
e     NaN
f     NaN
g     NaN
dtype: float64

::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.

### dataFrame

In [105]:
data = np.random.randn(4,3)

In [106]:
dataFrame = pd.DataFrame(data)

In [108]:
data

array([[ 1.63409705, -0.17220698,  0.50933033],
       [ 0.50688148,  0.09072549,  1.5374869 ],
       [ 0.54970952,  0.53550818, -0.13729646],
       [ 1.60457325,  0.88779746, -0.2165398 ]])

In [107]:
dataFrame

0         1         2
0  1.634097 -0.172207  0.509330
1  0.506881  0.090725  1.537487
2  0.549710  0.535508 -0.137296
3  1.604573  0.887797 -0.216540

In [109]:
dataFrame[0]

0    1.634097
1    0.506881
2    0.549710
3    1.604573
Name: 0, dtype: float64

In [121]:
yeniDataFrame = pd.DataFrame(data, index =["atil","atlas","osman", "mehmet"], columns = ["maas", "yas", "saat"])

In [111]:
yeniDataFrame

maas       yas      saat
atil    1.634097 -0.172207  0.509330
atlas   0.506881  0.090725  1.537487
osman   0.549710  0.535508 -0.137296
mehmet  1.604573  0.887797 -0.216540

In [112]:
yeniDataFrame["yas"]

atil     -0.172207
atlas     0.090725
osman     0.535508
mehmet    0.887797
Name: yas, dtype: float64

In [113]:
yeniDataFrame["saat"]

atil      0.509330
atlas     1.537487
osman    -0.137296
mehmet   -0.216540
Name: saat, dtype: float64

In [114]:
yeniDataFrame[["maas","yas"]] #fancy index

maas       yas
atil    1.634097 -0.172207
atlas   0.506881  0.090725
osman   0.549710  0.535508
mehmet  1.604573  0.887797

In [115]:
#yeniDataFrame["atil"] dersek column kısmında aramaya çalışır
#row bazlı arama için
#locate, yerini bul
yeniDataFrame.loc["atil"]

maas    1.634097
yas    -0.172207
saat    0.509330
Name: atil, dtype: float64

In [116]:
#index bazlı lokasyon araması
yeniDataFrame.iloc[1]

maas    0.506881
yas     0.090725
saat    1.537487
Name: atlas, dtype: float64

In [122]:
yeniDataFrame["emeklilikYasi"] = yeniDataFrame["yas"] + yeniDataFrame["yas"]

In [123]:
yeniDataFrame

maas       yas      saat  emeklilikYasi
atil    1.634097 -0.172207  0.509330      -0.344414
atlas   0.506881  0.090725  1.537487       0.181451
osman   0.549710  0.535508 -0.137296       1.071016
mehmet  1.604573  0.887797 -0.216540       1.775595

In [124]:
#col düşürme
yeniDataFrame.drop("emeklilikYasi", axis = 1)

maas       yas      saat
atil    1.634097 -0.172207  0.509330
atlas   0.506881  0.090725  1.537487
osman   0.549710  0.535508 -0.137296
mehmet  1.604573  0.887797 -0.216540

In [125]:
#row düşürme
yeniDataFrame.drop("mehmet", axis = 0) #default 0 zaten

maas       yas      saat  emeklilikYasi
atil   1.634097 -0.172207  0.509330      -0.344414
atlas  0.506881  0.090725  1.537487       0.181451
osman  0.549710  0.535508 -0.137296       1.071016

halihazırda olan dataframede bir değişilik yapmak istiyorsan unu belirtmen gerekiyor, fonksiyonlar dataframei bozmayacak şekilde tasarlanmışlar

In [126]:
yeniDataFrame.drop("mehmet", axis = 0, inplace=True) 

In [127]:
yeniDataFrame.loc["atil"]

maas             1.634097
yas             -0.172207
saat             0.509330
emeklilikYasi   -0.344414
Name: atil, dtype: float64

In [128]:
yeniDataFrame.loc["atil"]["yas"]

-0.17220698353918237

In [130]:
boolDataFrame = yeniDataFrame < 0

In [131]:
yeniDataFrame[boolDataFrame]

maas       yas      saat  emeklilikYasi
atil    NaN -0.172207       NaN      -0.344414
atlas   NaN       NaN       NaN            NaN
osman   NaN       NaN -0.137296            NaN

In [132]:
yeniDataFrame[yeniDataFrame < 0]

maas       yas      saat  emeklilikYasi
atil    NaN -0.172207       NaN      -0.344414
atlas   NaN       NaN       NaN            NaN
osman   NaN       NaN -0.137296            NaN

In [133]:
yeniDataFrame[yeniDataFrame["yas"]>0]

maas       yas      saat  emeklilikYasi
atlas  0.506881  0.090725  1.537487       0.181451
osman  0.549710  0.535508 -0.137296       1.071016

In [134]:
yeniDataFrame.reset_index()

index      maas       yas      saat  emeklilikYasi
0   atil  1.634097 -0.172207  0.509330      -0.344414
1  atlas  0.506881  0.090725  1.537487       0.181451
2  osman  0.549710  0.535508 -0.137296       1.071016

In [140]:
yeniDataFrame

maas       yas      saat  emeklilikYasi
atil   1.634097 -0.172207  0.509330      -0.344414
atlas  0.506881  0.090725  1.537487       0.181451
osman  0.549710  0.535508 -0.137296       1.071016

In [141]:
yeniIndexListesi = ["ati", "zey", "atl"]

In [142]:
yeniDataFrame["yeniIndexes"] = yeniIndexListesi

In [143]:
yeniDataFrame

maas       yas      saat  emeklilikYasi yeniIndexes
atil   1.634097 -0.172207  0.509330      -0.344414         ati
atlas  0.506881  0.090725  1.537487       0.181451         zey
osman  0.549710  0.535508 -0.137296       1.071016         atl

In [145]:
yeniDataFrame.set_index("yeniIndexes", inplace = True)

In [146]:
yeniDataFrame

maas       yas      saat  emeklilikYasi
yeniIndexes                                             
ati          1.634097 -0.172207  0.509330      -0.344414
zey          0.506881  0.090725  1.537487       0.181451
atl          0.549710  0.535508 -0.137296       1.071016

In [148]:
yeniDataFrame.loc["ati"]

maas             1.634097
yas             -0.172207
saat             0.509330
emeklilikYasi   -0.344414
Name: ati, dtype: float64

::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.

### multi index

In [149]:
ilkIndex = ["simpson","simpson", "simpson", "jen", "jen", "jen" ]

In [150]:
icIndex = ["homer", "bart", "marge", "cartman", "kenny", "kyle"]

In [151]:
birlesmisIndex = list(zip(ilkIndex, icIndex))

In [152]:
birlesmisIndex

[('simpson', 'homer'),
 ('simpson', 'bart'),
 ('simpson', 'marge'),
 ('jen', 'cartman'),
 ('jen', 'kenny'),
 ('jen', 'kyle')]

In [153]:
birlesmisIndex = pd.MultiIndex.from_tuples(birlesmisIndex)

In [154]:
birlesmisIndex

MultiIndex([('simpson',   'homer'),
            ('simpson',    'bart'),
            ('simpson',   'marge'),
            (    'jen', 'cartman'),
            (    'jen',   'kenny'),
            (    'jen',    'kyle')],
           )

In [155]:
type(birlesmisIndex)

pandas.core.indexes.multi.MultiIndex

In [156]:
cizgiFilmListem = [[40,"A"],[30,"B"], [40, "C"], [40,"D"],[50, "E"], [60,"F"]]

In [157]:
cizgiFilmNumpyDizisi = np.array(cizgiFilmListem)

In [159]:
cizgiFilmDataFrame = pd.DataFrame(cizgiFilmNumpyDizisi, index = birlesmisIndex, columns = ["yas", "meslek"])

In [160]:
cizgiFilmDataFrame

yas meslek
simpson homer    40      A
        bart     30      B
        marge    40      C
jen     cartman  40      D
        kenny    50      E
        kyle     60      F

In [161]:
cizgiFilmDataFrame.loc["simpson"]

yas meslek
homer  40      A
bart   30      B
marge  40      C

In [166]:
cizgiFilmDataFrame.loc["simpson"].loc["bart"]

yas       30
meslek     B
Name: bart, dtype: object

In [172]:
cizgiFilmDataFrame.index.names = ["soyad", "ad"]

In [173]:
cizgiFilmDataFrame

yas meslek
soyad   ad                
simpson homer    40      A
        bart     30      B
        marge    40      C
jen     cartman  40      D
        kenny    50      E
        kyle     60      F

::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.::.

## operasyonlar

### eksik veri analizi

In [175]:
sozlukVerisi = {"istanbul": [30,29,np.nan], "ankara":[20, np.nan,25],"izmir":[30,29,25]}
havaDurumuDF = pd.DataFrame(sozlukVerisi)

In [177]:
havaDurumuDF

istanbul  ankara  izmir
0      30.0    20.0     30
1      29.0     NaN     29
2       NaN    25.0     25

In [176]:
havaDurumuDF.dropna()

istanbul  ankara  izmir
0      30.0    20.0     30

In [178]:
havaDurumuDF.dropna(axis=1)

izmir
0     30
1     29
2     25

In [179]:
yeniVeri = {"istanbul": [30,29,np.nan], "ankara":[20, np.nan,25],"izmir":[30,29,25], "antalya":[45, np.nan, np.nan]}
yeniDF = pd.DataFrame(yeniVeri)

In [180]:
yeniDF

istanbul  ankara  izmir  antalya
0      30.0    20.0     30     45.0
1      29.0     NaN     29      NaN
2       NaN    25.0     25      NaN

In [181]:
#iki tane boş verisi olanı düşüreceğiz
yeniDF.dropna(axis=1, thresh=2)

istanbul  ankara  izmir
0      30.0    20.0     30
1      29.0     NaN     29
2       NaN    25.0     25

In [182]:
#nan olan her yere 10 koymak istiyorum
yeniDF.fillna(10)

istanbul  ankara  izmir  antalya
0      30.0    20.0     30     45.0
1      29.0    10.0     29     10.0
2      10.0    25.0     25     10.0

### gruplandırma

groupby

In [205]:
maas = {"departman": ["yazılım", "yazılım", "pazarlama", "pazarlama", "hukuk", "hukuk"],
        "calisanlar": ["ahmet", "mehmet", "atil","burak","zeynep", "fatma"],
        "maas": [500,500,400,600,700,400]
        }

In [206]:
maasDF = pd.DataFrame(maas)

In [207]:
maasDF

departman calisanlar  maas
0    yazılım      ahmet   500
1    yazılım     mehmet   500
2  pazarlama       atil   400
3  pazarlama      burak   600
4      hukuk     zeynep   700
5      hukuk      fatma   400

In [210]:
grupO = maasDF.groupby("departman")

In [213]:
grupO

In [211]:
grupO.count()

calisanlar  maas
departman                  
hukuk               2     2
pazarlama           2     2
yazılım             2     2

In [222]:
grupO.mean()  #bu neden çalışmıyor bilmiyorum, hatayı detaylı incelemedim

TypeError: agg function failed [how->mean,dtype->object]

In [216]:
grupO.max()

calisanlar  maas
departman                 
hukuk         zeynep   700
pazarlama      burak   600
yazılım       mehmet   500

In [219]:
grupO.min()

calisanlar  maas
departman                 
hukuk          fatma   400
pazarlama       atil   400
yazılım        ahmet   500

In [221]:
grupO.describe()

maas                                                      
          count   mean         std    min    25%    50%    75%    max
departman                                                            
hukuk       2.0  550.0  212.132034  400.0  475.0  550.0  625.0  700.0
pazarlama   2.0  500.0  141.421356  400.0  450.0  500.0  550.0  600.0
yazılım     2.0  500.0    0.000000  500.0  500.0  500.0  500.0  500.0

### concat - merge

In [225]:
sozluk1 = {"isim": ["ayse", "fatma", "hayriye"],
"spor": ["voleybol", "tenis","yüzme"],
"kalori": [100,110,150] }

sozluk2 = { "isim": ["ahmet", "mehmet", "veli"],
"spor": ["futbol", "tenis","yüzme"],
"kalori": [300,350,390]}

sozluk3 = {"isim": ["zehra","eda","melisa"],
"spor": ["voleybol", "tenis","ice-skating"],
"kalori": [250,245,260] }

In [226]:
df1 = pd.DataFrame(sozluk1, index = [0,1,2])
df2 = pd.DataFrame(sozluk2, index = [3,4,5])
df3 = pd.DataFrame(sozluk3, index = [6,7,8])

In [228]:
pd.concat([df1,df2,df3])

isim      spor  kalori
0     ayse  voleybol     100
1    fatma     tenis     110
2  hayriye     yüzme     150
3    ahmet  voleybol     300
4   mehmet     tenis     350
5     veli     yüzme     390
6    zehra  voleybol     250
7      eda     tenis     245
8   melisa     yüzme     260

In [229]:
pd.concat([df1,df2,df3], axis=1)

isim      spor  kalori    isim      spor  kalori    isim      spor  \
0     ayse  voleybol   100.0     NaN       NaN     NaN     NaN       NaN   
1    fatma     tenis   110.0     NaN       NaN     NaN     NaN       NaN   
2  hayriye     yüzme   150.0     NaN       NaN     NaN     NaN       NaN   
3      NaN       NaN     NaN   ahmet  voleybol   300.0     NaN       NaN   
4      NaN       NaN     NaN  mehmet     tenis   350.0     NaN       NaN   
5      NaN       NaN     NaN    veli     yüzme   390.0     NaN       NaN   
6      NaN       NaN     NaN     NaN       NaN     NaN   zehra  voleybol   
7      NaN       NaN     NaN     NaN       NaN     NaN     eda     tenis   
8      NaN       NaN     NaN     NaN       NaN     NaN  melisa     yüzme   

   kalori  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
5     NaN  
6   250.0  
7   245.0  
8   260.0

In [230]:
sozluk1 = {"isim": ["ayse", "fatma", "hayriye"],
"spor": ["voleybol", "tenis","yüzme"]}

sozluk2 = {"isim": ["ayse", "fatma", "hayriye"],
"kalori": [100,110,150] }


In [231]:
df1 = pd.DataFrame(sozluk1)
df2 = pd.DataFrame(sozluk2)

In [232]:
df1

isim      spor
0     ayse  voleybol
1    fatma     tenis
2  hayriye     yüzme

In [233]:
df2

isim  kalori
0     ayse     100
1    fatma     110
2  hayriye     150

In [234]:
pd.merge(df1, df2, on="isim")

isim      spor  kalori
0     ayse  voleybol     100
1    fatma     tenis     110
2  hayriye     yüzme     150